#!/usr/bin/env python3
"""Generate frontend/src/lib/rubric-categories.ts from contracts/DeFiLens.py.

    python3 tools/gen_categories.py          # write
    python3 tools/gen_categories.py --check  # exit 1 if the file is stale

The docs page renders the rubric's category table. Copying it by hand would
mean the site could claim one thing while the contract scored another, so it is
generated and `tools/audit.sh` runs --check.
"""
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "contracts" / "DeFiLens.py"
OUT = ROOT / "frontend" / "src" / "lib" / "rubric-categories.ts"

LABELS = {
    7: "lowest-risk category", 6: "low-risk category", 5: "lower-risk category",
    4: "moderate-risk category", 3: "elevated-risk category",
    2: "high-risk category", 1: "very high-risk category", 0: "highest-risk category",
}
WHY = {
    7: "Custody stays with the user, or the contract surface is tiny.",
    6: "Well-understood mechanisms holding deposits in a single, audited surface.",
    5: "Real but bounded exposure — a peg, a collateral position, an underwriter.",
    4: "Deposits are routed through strategies that can themselves fail.",
    3: "Leverage, exotic collateral, or a governance-controlled peg.",
    2: "Leverage on leverage. A bad hour moves more than the position.",
    1: "A bridge concentrates every chain's deposits behind one validator set.",
    0: "The house always wins, and says so.",
}


def render() -> str:
    src = SRC.read_text(encoding="utf8")
    m = re.search(r"^CATEGORY_RISK = \((.*?)^\)$", src, re.S | re.M)
    if not m:
        raise SystemExit("CATEGORY_RISK not found in the contract")
    table = ast.literal_eval("(" + m.group(1) + ")")
    default = int(re.search(r"^CATEGORY_DEFAULT\s*=\s*(\d+)", src, re.M).group(1))
    rows = [
        {"ordinal": o, "label": LABELS[o], "why": WHY[o], "categories": list(names)}
        for o, names in table
    ]
    return (
        "/**\n"
        " * The rubric's category table, MIRRORED FROM `contracts/DeFiLens.py`.\n"
        " *\n"
        " * Generated by tools/gen_categories.py, never hand-edited: tools/audit.sh\n"
        " * regenerates it and fails if this file differs. A docs page that quietly\n"
        " * disagreed with the contract it documents would be worse than no docs page.\n"
        " */\n\n"
        f"export const CATEGORY_DEFAULT = {default};\n\n"
        "export type CategoryBand = {\n"
        "  ordinal: number;\n  label: string;\n  why: string;\n  categories: string[];\n};\n\n"
        "export const CATEGORY_BANDS: CategoryBand[] = "
        + json.dumps(rows, indent=2)
        + ";\n"
    )


if __name__ == "__main__":
    want = render()
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf8") if OUT.exists() else ""
        if have != want:
            print("STALE")
            sys.exit(1)
        print("OK")
    else:
        OUT.write_text(want, encoding="utf8")
        print(f"wrote {OUT.relative_to(ROOT)}")
