/**
 * The rubric's category table, MIRRORED FROM `contracts/DeFiLens.py`.
 *
 * Generated by tools/gen_categories.py, never hand-edited: tools/audit.sh
 * regenerates it and fails if this file differs. A docs page that quietly
 * disagreed with the contract it documents would be worse than no docs page.
 */

export const CATEGORY_DEFAULT = 3;

export type CategoryBand = {
  ordinal: number;
  label: string;
  why: string;
  categories: string[];
};

export const CATEGORY_BANDS: CategoryBand[] = [
  {
    "ordinal": 7,
    "label": "lowest-risk category",
    "why": "Custody stays with the user, or the contract surface is tiny.",
    "categories": [
      "Liquid Staking",
      "Staking Pool",
      "Oracle",
      "Portfolio Tracker",
      "Coins Tracker",
      "Domains",
      "Identity & Reputation",
      "Wallets",
      "Developer Tools",
      "Interface",
      "Onchain Voting",
      "Token Locker"
    ]
  },
  {
    "ordinal": 6,
    "label": "low-risk category",
    "why": "Well-understood mechanisms holding deposits in a single, audited surface.",
    "categories": [
      "Lending",
      "Dexs",
      "DEX Aggregator",
      "Payments",
      "Chain Bribes",
      "Governance Incentives",
      "Liquidity Manager",
      "Indexes",
      "Treasury Manager",
      "Decentralized BTC",
      "Anchor BTC"
    ]
  },
  {
    "ordinal": 5,
    "label": "lower-risk category",
    "why": "Real but bounded exposure \u2014 a peg, a collateral position, an underwriter.",
    "categories": [
      "CDP",
      "CDP Manager",
      "Stablecoin Issuer",
      "Stablecoin Wrapper",
      "Collateral Management",
      "Collateral Markets",
      "Liquidations",
      "RWA",
      "Insurance",
      "DCA Tools",
      "Trading App",
      "Services",
      "Risk Curators",
      "Security Extension",
      "Bug Bounty"
    ]
  },
  {
    "ordinal": 4,
    "label": "moderate-risk category",
    "why": "Deposits are routed through strategies that can themselves fail.",
    "categories": [
      "Yield",
      "Yield Aggregator",
      "Farm",
      "Liquid Restaking",
      "Restaking",
      "Restaked BTC",
      "Liquidity Automation",
      "ve-Incentive Automator",
      "Onchain Capital Allocator",
      "Secondary Debt Markets",
      "SoFi",
      "Reserve Currency",
      "DePIN",
      "Mining Pools"
    ]
  },
  {
    "ordinal": 3,
    "label": "elevated-risk category",
    "why": "Leverage, exotic collateral, or a governance-controlled peg.",
    "categories": [
      "Synthetics",
      "Options",
      "Options Vault",
      "Exotic Options",
      "Interest Rate Derivatives",
      "Basis Trading",
      "Algo-Stables",
      "Partially Algorithmic Stablecoin",
      "Dual-Token Stablecoin",
      "NFT Lending",
      "NftFi",
      "NFT Marketplace",
      "NFT Launchpad",
      "NFT Automated Strategies",
      "Prediction Market",
      "Launchpad",
      "Privacy",
      "MEV",
      "Block Builders",
      "DOR",
      "Decentralized AI",
      "AI Agents",
      "Staking Rental",
      "OTC Marketplace",
      "CeDeFi",
      "Crypto Card Issuer",
      "DAO Service Provider",
      "Foundation",
      "Private Investment Platform",
      "Charity Fundraising",
      "Video Infrastructure",
      "Physical TCG",
      "Telegram Bot",
      "Gaming",
      "Meme"
    ]
  },
  {
    "ordinal": 2,
    "label": "high-risk category",
    "why": "Leverage on leverage. A bad hour moves more than the position.",
    "categories": [
      "Derivatives",
      "Leveraged Farming",
      "Uncollateralized Lending",
      "Volume Boosting"
    ]
  },
  {
    "ordinal": 1,
    "label": "very high-risk category",
    "why": "A bridge concentrates every chain's deposits behind one validator set.",
    "categories": [
      "Bridge",
      "Bridge Aggregator",
      "Bridge Aggregators",
      "Cross Chain Bridge",
      "Canonical Bridge"
    ]
  },
  {
    "ordinal": 0,
    "label": "highest-risk category",
    "why": "The house always wins, and says so.",
    "categories": [
      "Ponzi",
      "Luck Games",
      "Yield Lottery",
      "Gamified Mining"
    ]
  }
];
